name: shmr_finance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  build_runner: ^2.4.15
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  freezed: ^3.0.6
  connectivity_plus: ^6.1.4
  flutter_svg: ^2.1.0
  json_annotation: ^4.9.0
  yx_scope: ^1.0.2
  yx_scope_flutter: ^1.0.2
  sembast: ^3.8.3
  synchronized: ^3.3.0+3
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  shake_gesture: ^1.2.0
  fuzzy: <1.0.0
  collection: ^1.19.0

  shmr_charts_package:
    path: ./shmr_charts_package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  generate: true

  assets:
     - assets/icons/